### ISSUE TITLE
ModuleNotFoundError: No module named 'mazelib.generator'

### ISSUE THREAD

**Issue by wer310** [john-science/mazelib#151] opened 2024-03-19 08:32 UTC
```
ModuleNotFoundError: No module named 'mazelib.generator'
```

**Comment by wer310** [comment] 2024-03-19 08:32
I have a module

**Comment by john-science** [comment] 2024-04-19 22:56
> I have a module

Are you saying the problem is resolved?

If not, can you give me two things:

1. **Information about your system**: OS version, Python version
2. **Copy/Paste** the screenshot of what you typed to get this.

**Comment by john-science** [comment] 2024-11-16 21:21
I will close this ticket, as I never understood the question.

Feel free to ask for more help, or give me a stack trace so I can see your issue.

**Closed by john-science** 2024-11-16 21:21 UTC
